# Question-Answering Config
defaults:
  - base_eval
  - _self_
# Data
dataset: "squad"
base_path: './../data'
# Eval
task_lm: "distilgpt2"
prompt: "orate practicable practicable practicable practicable"

