# Question-Answering Config
defaults:
  - base_qa
  - _self_
# Data
dataset: "squad"
# Reward
task_lm: "distilgpt2"
compute_zscore: True
lower_outputs: true
control_output_length: true
# Single Prompt Model
prompt_length: 5
prompt_train_batch_size: 2
prompt_infer_batch_size: 16
# LM Adaptor Model
logit_bias: -10
# SQL Module
reward_shaping_old_min: 0
reward_shaping_old_max: 1
reward_shaping_new_min: -50
reward_shaping_new_max: 50
top_k: 5
# Trainer
train_batch_size: 2
max_train_steps: 6000
train_shuffle: false
eval_batch_size: 16
eval_steps: 500
save_steps: 500
learning_rate: 1e-4
random_seed: null
report_to_wandb: false